return {
  name = "Dap Debug",
  b = { "<cmd>DapToggleBreakpoint<cr>", "Set breakpoint" },
  B = { "<cmd>SetBreakPointCondition<cr>", "Set breakpoint condition" },
  o = { "<cmd>DapStepOut<cr>", "Step out" },
  i = { "<cmd>DapStepInto<cr>", "Step Into" },
  v = { "<cmd>DapStepOver<cr>", "Step Over" },
  c = { "<cmd>DapContinue<cr>", "Continue" },
  u = { "<cmd>DapRuntoCursor<cr>", "Run to cursor" },
  t = { "<cmd>DapTerminate<cr>", "Terminate" },
  R = { "<cmd>ClearBreakpoints<cr>", "Clear breakpoint" },
  e = { "<cmd>SetExceptionBreakpoints<cr>", "Debug set exception breakpoint" },
  n = { "<cmd>DebugNode<cr>", "Debug node" },
  J = { "<cmd>DebugJest<cr>", "Debug jest" },
  h = { "<cmd>DapUiHover<cr>", "Dap UI Widgets Hover" },
  s = { "<cmd>DapUiScopes<cr>", "Dap UI Widgets Scopes" },
  k = { "<cmd>DapUp<cr>zz", "Dap Up" },
  j = { "<cmd>DapDown<cr>zz", "Dap down" },
  r = { "<cmd>DapOpenRepl<cr><c-w>l", "Open repl" },
  f = { "<cmd>Telescope dap frames<cr>", "Dap frames" },
  l = { "<cmd>Telescope dap list_breakpoints<cr>", "List breakpoints" },
  O = { "<cmd>DapUiOpen<cr>", "Dap UI Open" },
  C = { "<cmd>DapUiClose<cr>", "Dap UI Close" },
}
