return {
  name = "LeetCode",
  m = { "<cmd>Leet<cr>", "Menu" },
  c = { "<cmd>Leet console<cr>", "Console" },
  h = { "<cmd>Leet hints<cr>", "Hints" },
  q = { "<cmd>Leet tabs<cr>", "Tabs" },
  l = { "<cmd>Leet lang<cr>", "Language" },
  d = { "<cmd>Leet desc<cr>", "Description" },
  r = { "<cmd>Leet run<cr>", "Run" },
  s = { "<cmd>Leet submit<cr>", "Submit" },
  a = { "<cmd>Leet random<cr>", "Random" },
  y = { "<cmd>Leet daily<cr>", "Daily" },
  t = { "<cmd>Leet list<cr>", "List" },
  i = { "<cmd>Leet info<cr>", "Info" },
}
