return {
  name = "Obsidian",
  r = { "<cmd>ObsidianBacklinks<cr>", "References list" },
  t = { "<cmd>ObsidianToday<cr>", "Daily note" },
  d = { "<cmd>ObsidianYesterday<cr>", "Daily note for yesterday" },
  o = { "<cmd>ObsidianOpen<cr>", "Open in obsidian" },
  n = { "<cmd>ObsidianNew<cr>", "New note" },
  s = { "<cmd>ObsidianSearch<cr>", "Search for notes" },
  q = { "<cmd>ObsidianQuickSwitch<cr>", "Quickly switch" },
  l = { "<cmd>ObsidianLink<cr>", "Link to a note" },
  c = { "<cmd>ObsidianLinkNew<cr>", "Create note and link" },
  f = { "<cmd>ObsidianFollowLink<cr>", "Follow note under cursor" },
  i = { "<cmd>ObsidianTemplate<cr>", "Insert template" },
  w = { "<cmd>ObsidianWorkspace<cr>", "Switch workspace" },
  e = { "<cmd>EnableObsidian<cr>", "Enable obsidian" },
}
